apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "spring test"
  description: "spring test"
  annotations:
    github.com/project-slug: 
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "dinesh-dev-test|DineshKumar_Chandrasekaran@comcast.com"
